### ISSUE TITLE
Prevent file content in ansible output

### ISSUE THREAD

**Issue by nielscil** [mother-of-all-self-hosting/ansible-role-aux#1]
When using this role with content defined in the vars, it shows the whole item including the content in the ansible output. This gives a lot of noice and can possible leak secrets if the output is logged. 

My suggestion is to add a `loop_control` with `label` to the following task, so that it only prints the destination.

https://github.com/mother-of-all-self-hosting/ansible-role-aux/blob/206626994c4fd8fba51912acdf172886f1a4d7f3/tasks/setup.yml#L12

something like this:

```
...
with_items: "{{ aux_file_definitions }}"
loop_control:
    label: "{{ item.dest }}"
```

**Comment by spantaleev** [comment]
Sounds good! Would you send a PR?
